---
title: "Untitled"
author: "Melisa Gumus"
date: "2023-12-07"
output: html_document
---

# Load packages
```{r}
# packages
library(tidyverse)
library(reshape2)
# install.packages('network')
# library(network)

install.packages('visNetwork')
# install.packages('networkD3')
library(visNetwork)
# library(networkD3)

install.packages('igraph')
library(igraph)
  
```


# Clean env
```{r setup, include=FALSE}
# clear environment
rm(list = ls())

load("../../output/Rdata/00_import_data_subfields+MTL_all_data.RDATA")
```


```{r}
test <-
  R_data_stream %>%
  melt()

R_melted <-
  cbind(test$ID, stringr::str_split_fixed(test$variable, "/", 2)) %>%
  cbind(test$value) %>%
  data.frame()

colnames(R_melted) <- c("sbj", "reg1", "reg2", "stream")

# get rid of stratum
R_melted <- R_melted[-c(grep("stratum", R_melted$reg1), grep("stratum", R_melted$reg2),
                            grep("R_PHC", R_melted$reg1), grep("R_PHC", R_melted$reg2),
                            grep("R_PRC", R_melted$reg1), grep("R_PRC", R_melted$reg2)),]

```


```{r}
regions_1 <-
  R_melted %>%
  distinct(reg1) %>%
  rename(label = reg1)

regions_2 <-
  R_melted %>%
  distinct(reg2) %>%
  rename(label = reg2)

nodes <- full_join(regions_1, regions_2, by = "label")

nodes <- nodes %>% rowid_to_column("id")

per_route <-
  R_melted %>%  
  group_by(reg1, reg2) %>%
  summarise(weight = stream) %>% 
  ungroup()

per_route$weight <- as.integer(per_route$weight)
edges <- per_route %>% 
  left_join(nodes, by = c("reg1" = "label")) %>% 
  rename(from = id)

edges <- edges %>% 
  left_join(nodes, by = c("reg2" = "label")) %>% 
  rename(to = id)

edges <- select(edges, from, to, weight)

## make igraph object
edges_igraph <- graph_from_data_frame(as.data.frame(edges), directed = F) #, mode="undirected", weighted=T)

```


# 1 = SUB
# 2 = DG
# 3 = CA23
# 4 = ERC
# 5 = CA1

# louvain
```{r}
net <- cluster_louvain(edges_igraph)

plot(net, edges_igraph)

```

```{r}
V(edges_igraph)$name[net$membership==1]
V(edges_igraph)$name[net$membership==2]

```




# END 