---
title: "02_volume_corrected"
output: html_document
---


```{r setup, include=FALSE}
# clear environment
rm(list = ls())

# packages
library(tidyverse)
library(reshape2)
library(ggplot2)

```


# Read in volume data
```{r}
# clear environment
rm(list = ls())

#modality <- c("stream", "FA", "AD", "RD", "MD")
headers <- read.table("../../labels/subfield_MTL_labels.txt", header=T, sep="")

# for (m in modality){
temp <- list.files(path="../../data/quality-control/volume/subjects", pattern="*.csv", recursive = T, full.names = T)
for (k in 1:length(temp)) assign(temp[k], read.csv(temp[k], header=F, sep=","))

vol_data <- list()
for (i in 1:length(temp)){
  vol_data[[i]] <- mget(temp[i])
  names(vol_data[[i]]) <- temp[i]
}

# Subjects in a list
#sbj_list <- as.list(grep("stream", stream_data))

columns <- c()
for (i in 1:length(headers$Clear.Label)){
  for (t in 1:length(headers$Clear.Label)){
    column_name <- paste(headers$Clear.Label[i], headers$Clear.Label[t], sep="/")
    columns <- append(columns, column_name)
  }
}

```

# Separate Right and Left hemisphere
```{r}
right_coor <- grep("R_", headers$Clear.Label)
left_coor <- grep("L_", headers$Clear.Label)

# Separate R and L labels
R_columns <- c()
for (i in right_coor) {
  for (t in right_coor){
    R_column_name <- paste(headers$Clear.Label[i], headers$Clear.Label[t], sep="/")
    R_columns <- append(R_columns, R_column_name)
  }
}

L_columns <- c()
for (j in left_coor){
  for (k in left_coor){
    L_column_name <- paste(headers$Clear.Label[j], headers$Clear.Label[k], sep="/")
    L_columns <- append(L_columns, L_column_name)
  }
}
```

# Gather all volumes
```{r}
#### Take upper/lower triangular ######
to.upper<-function(X) t(X)[lower.tri(X,diag=FALSE)]

modality <- c("vol")
# Right 
for (m in modality){
  R_upper_temp <- data.frame()
  for (i in 1:length(get(paste0(m, "_data")))) {
    v1 <- get(paste0(m, "_data"))[[i]][[1]][,1]
    v2 <- get(paste0(m, "_data"))[[i]][[1]][,1]
    vol_m<-matrix(rep(0,length(v1)*length(v2)), nrow=length(v1))
    
    for(k in 1:length(v1)){
      for(j in 1:length(v2)){
        vol_m[k,j] <- (v1[k]+v2[j])/2
      }
    }

    person_temp <-
      data.frame(t(to.upper(vol_m
        # matrix(unlist(get(paste0(m, "_data"))[i]), 
        #                            nrow = length(headers$Clear.Label),
        #                            ncol = length(headers$Clear.Label))
                            [right_coor, right_coor])))
    # person_temp$ID <- sub(paste0("../../../data/HCP_connectomes/connect_hipp+MTL_", m, "/sub-"),"",
    #                       (sub(paste0("_MTL_hipp_connectome_", m, ".csv"),"",
    #                            names(get(paste0(m, "_data"))[[i]]))))
    person_temp$ID <- 
      strsplit(names(get(paste0(m, "_data"))[[i]]), "sub-")[[1]][2] %>%
      strsplit("_") %>%
      .[[1]] %>%
      .[[1]]
    
    R_upper_temp <- rbind(R_upper_temp, person_temp)
  }
  R_conn <- matrix(R_columns,
                   nrow = length(headers$Clear.Label[right_coor]),
                   ncol = length(headers$Clear.Label[right_coor]))
  R_upper_columns <- to.upper(R_conn)
  R_upper_columns <- c(R_upper_columns, "ID")
  colnames(R_upper_temp) <- c(R_upper_columns)
  
  assign(paste0("R_data_", m), R_upper_temp)
}

# 
# sub(paste0("_MTL_hipp_connectome_", m, ".csv"), "",names(get(paste0(m, "_data"))[[i]]))
# person_test$ID <- sub("../../data/connect_stream/conn/sub-","",
#                         (sub("_hipp_connectome_stream.csv","",
#                              names(stream_data[[i]]))))
# 

# Left
for (m in modality){
  L_upper_temp <- data.frame()
  for (i in 1:length(get(paste0(m, "_data")))) {
    v1 <- get(paste0(m, "_data"))[[i]][[1]][,1]
    v2 <- get(paste0(m, "_data"))[[i]][[1]][,1]
    vol_m<-matrix(rep(0,length(v1)*length(v2)), nrow=length(v1))
    
    for(k in 1:length(v1)){
      for(j in 1:length(v2)){
        vol_m[k,j] <- (v1[k]+v2[j])/2
      }
    }

    person_temp <-
      data.frame(t(to.upper(vol_m
        # matrix(unlist(get(paste0(m, "_data"))[i]), 
        #                            nrow = length(headers$Clear.Label),
        #                            ncol = length(headers$Clear.Label))
                            [left_coor, left_coor])))
    # person_temp$ID <- sub(paste0("../../../data/HCP_connectomes/connect_hipp+MTL_", m, "/sub-"),"",
    #                       (sub(paste0("_MTL_hipp_connectome_", m, ".csv"),"",
    #                            names(get(paste0(m, "_data"))[[i]]))))
    person_temp$ID <- 
      strsplit(names(get(paste0(m, "_data"))[[i]]), "sub-")[[1]][2] %>%
      strsplit("_") %>%
      .[[1]] %>%
      .[[1]]
        
    L_upper_temp <- rbind(L_upper_temp, person_temp)
  }
  L_conn <- matrix(L_columns,
                   nrow = length(headers$Clear.Label[left_coor]),
                   ncol = length(headers$Clear.Label[left_coor]))
  L_upper_columns <- to.upper(L_conn)
  L_upper_columns <- c(L_upper_columns, "ID")
  colnames(L_upper_temp) <- c(L_upper_columns)
  
  assign(paste0("L_data_", m), L_upper_temp)
}

```


# Read in connectomes
```{r}
# data
load("../../output/Rdata/00_import_data_MTL_hipp.RDATA")

# Define modalities
modality <- c("stream") #, "FA", "AD", "RD", "MD")

modality_clean <- c("Steamline Count") #,
                    # "Fractional Anisotropy",
                    # "Axial Diffusivity",
                    # "Radial Diffusivity",
                    # "Mean Diffusivity")

```

# TSP 
```{r}
tsp <- read.csv("../../data/hipp_paths_edit/tracks_edited_exc.csv", header = F)
colnames(tsp) <- c("ID", "side", "variable", "value")
tsp$variable <- gsub("_", "/", tsp$variable)

tsp_wide <-
  tsp %>% pivot_wider(names_from = c("side", "variable"))

L_data_stream$`L_CA2CA3/L_CA4DG`<- tsp_wide$`L_CA4DG/CA2CA3`
L_data_stream$`L_CA2CA3/L_CA1` <- tsp_wide$`L_CA2CA3/CA1`
#L_data_stream <- merge(L_data_stream, tsp_wide[,c("ID","L_CA2CA3/CA1","L_CA4DG/CA2CA3")], by = "ID")

R_data_stream$`R_CA2CA3/R_CA4DG` <- tsp_wide$`R_CA4DG/CA2CA3`
R_data_stream$`R_CA2CA3/R_CA1` <- tsp_wide$`R_CA2CA3/CA1`
#R_data_stream <- merge(R_data_stream, tsp_wide[,c("ID","R_CA2CA3/CA1","R_CA4DG/CA2CA3")], by = "ID")

```

# Correct for volume
```{r}

#L_data_cor <- as.data.frame(matrix(nrow=831, ncol=1))
L_data_cor <- c()
for (i in 1:28) {
  temp_cor <- L_data_stream[,i]/L_data_vol[,i]
  L_data_cor <- cbind(L_data_cor, temp_cor)
}
L_data_cor <- data.frame(L_data_cor)
L_data_cor$ID <- L_data_stream$ID
colnames(L_data_cor) <- colnames(L_data_vol)


#L_data_cor <- as.data.frame(matrix(nrow=831, ncol=1))
R_data_cor <- c()
for (i in 1:28) {
  temp_cor <- R_data_stream[,i]/R_data_vol[,i]
  R_data_cor <- cbind(R_data_cor, temp_cor)
}
R_data_cor <- data.frame(R_data_cor)
R_data_cor$ID <- R_data_stream$ID
colnames(R_data_cor) <- colnames(R_data_vol)

```

##### Volume corrected streamlines ####
```{r}
modality <- c("cor")

modality_clean <- c("Scaled streamline density")

for (m in 1:length(modality)){
  L_temp_ready <- melt(get(paste0("L_data_", modality[m])))
  R_temp_ready <- melt(get(paste0("R_data_", modality[m])))
       
  # get rid of PRC PHC
  R_temp_heat <-
    R_temp_ready[-which(grepl("PRC", R_temp_ready$variable) |
                   grepl("PHC", R_temp_ready$variable) |
                   grepl("stratum", R_temp_ready$variable)
                     ),]
  
  L_temp_heat <-
    L_temp_ready[-which(grepl("PRC", L_temp_ready$variable) |
                   grepl("PHC", L_temp_ready$variable) |
                   grepl("stratum", L_temp_ready$variable)
                     ),]
  
  # Clean up the names
  R_temp_heat$variable <-
    gsub('R_subiculum', 'SUB',
         gsub("R_CA1", "CA1",
              gsub("R_CA4DG", "CA4DG",
                   gsub("R_CA2CA3", "CA2CA3",
                        gsub("R_ERC", "ERC", R_temp_heat$variable)))))
  R_temp_heat$side <- "R"
  
  L_temp_heat$variable <-
    gsub('L_subiculum', 'SUB',
         gsub("L_CA1", "CA1",
              gsub("L_CA4DG", "CA4DG",
                   gsub("L_CA2CA3", "CA2CA3",
                        gsub("L_ERC", "ERC", L_temp_heat$variable)))))
  L_temp_heat$side <- "L"
  
  temp_heat <- rbind(L_temp_heat, R_temp_heat)
  # temp_rois <- c("ERC/CA1",
  #                 "CA4DG/SUB",
  #                 "CA2CA3/CA4DG",
  #                 "CA2CA3/CA1",
  #                 "SUB/CA1",
  #                 "ERC/SUB")
  
  temp_heat_clean <-
    temp_heat %>%
    subset(temp_heat$variable == "ERC/CA1" |
             #temp_heat$variable == "CA4DG/SUB" |
             temp_heat$variable == "CA2CA3/CA4DG" |
             temp_heat$variable == "CA2CA3/CA1" |
             temp_heat$variable == "SUB/CA1" |
             temp_heat$variable == "ERC/SUB")
  
  temp_heat_clean$side <- 
    factor(temp_heat_clean$side, levels = c("R", "L"))
  
  temp_heat_clean$variable <-
    factor(temp_heat_clean$variable,
           levels = c("ERC/CA1",
                      #"CA4DG/SUB",
                      "CA2CA3/CA4DG",
                      "CA2CA3/CA1",
                      "SUB/CA1",
                      "ERC/SUB"
                      ))
  
  plt_cor <- 
    (ggplot(temp_heat_clean, aes(x=variable, y=value, fill=variable)) +
     geom_boxplot(width = .44,
           #outlier.shape=8,
           outlier.size = 0.2,
           #notch=TRUE,
           aes(y = value, fill = side)) +
      scale_x_discrete(#name = "Hemisphere",
                breaks = c("ERC/CA1",
                #"CA4DG/SUB",
                "CA2CA3/CA4DG",
                "CA2CA3/CA1",
                "SUB/CA1",
                "ERC/SUB"),
                labels = c("ERC/CA1",
                #"DG/SUB",
                "DG/CA3",
                "CA3/CA1",
                "SUB/CA1",
                "ERC/SUB"))+
      scale_fill_manual(name = "Hemisphere",
                      breaks = c("R", "L"),
                      values=c("indianred4", #"peachpuff4",
                               "indianred1" #"peru"
                               ),
                      labels = c("Right", "Left"))+
      ylab(modality_clean[m]) +
      xlab(" ") +
      stat_compare_means(aes(group = side), label = "p.signif", paired = TRUE) +
      theme(
        legend.title = element_text(colour="black", size = 12, face = "bold"),
        axis.text.x=element_text(size=9,color="black", face="bold"),
        axis.text.y=element_text(size=12,color="black"),
        axis.line.y.left =element_line(size=0.5, color = "black"),
        axis.line.x.bottom =element_line(size=0.5, color = "black"),
        axis.title.x = element_text(color="black", size=13, face="bold", vjust=-0.8), # vjust=0.5),
        axis.title.y = element_text(color="black", size=13, face="bold", vjust=1.5),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "white", color = "white"),
        legend.background = element_rect(fill = "white", color = "white")
        #plot.background = element_rect(fill = "transparent", color = NA)# vjust=0.5)
        )) %>%
    ggsave(paste0("../../plots/distribution/pathways_boxplot_volume_corrected_", modality[m], ".png"), .,
           width = 6, height = 3, dpi = 800 #,
           #bg = "transparent"
           )
}

plt_cor

```

##### END
