---
title: "05_cognition"
author: "Melisa Gumus"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# packages
library(tidyverse)
library(reshape2)
library(ggpubr)
library(ggplot2)
library(gridExtra)
library(lme4)
install.packages("factoextra")
library(factoextra)
library(modelbased)
library(ggeffects)

```

# Load data
```{r}
# clear environment
rm(list = ls())

temp_data <- read.csv("../../data/behaviour/HCP_behavioural_data.csv") #, header=T, sep="")
sbjs <- read.table("../../data/behaviour/final_subjects.txt") #, header=T, sep="")
beh_data <- temp_data[temp_data$Subject %in% sbjs$V1,]
beh_data$ID <- beh_data$Subject
load("../../output/Rdata/00_import_data_MTL_hipp_data.RDATA")


# TSP 
tsp <- read.csv("../../data/hipp_paths_edit/tracks_edited_exc.csv", header = F)
colnames(tsp) <- c("ID", "side", "variable", "value")
tsp$variable <- gsub("_", "/", tsp$variable)

tsp_wide <-
  tsp %>% pivot_wider(names_from = c("side", "variable")) 

opts.l <- lmerControl(optimizer='optimx',calc.derivs=FALSE,
                      optCtrl=list(method='bobyqa',starttests=FALSE,kkt=FALSE))
opts.g <- glmerControl(optimizer='optimx',calc.derivs=FALSE,
                       optCtrl=list(method='bobyqa',starttests=FALSE,kkt=FALSE))
```

# Exclude PRC, PHC and stratum
```{r}
stream_data <- merge(L_data_stream, R_data_stream, by = "ID") %>%
  merge(tsp_wide, by = "ID")
stream_beh_temp <- merge(stream_data, beh_data, by = "ID")

exc_col <-
  colnames(stream_beh_temp)[grepl("PRC|PHC|stratum", colnames(stream_beh_temp))]

stream_beh_data <-
  stream_beh_temp[,!(names(stream_beh_temp) %in% exc_col)]

stream_beh_data$Gender <- as.factor(stream_beh_data$Gender)
stream_beh_data$Age <- as.factor(stream_beh_data$Age)
stream_beh_data$ID <- factor(stream_beh_data$ID)

# NEW 
stream_beh_data <-
  stream_beh_data[,!(names(stream_beh_data) %in% c("L_ERC/L_CA4DG", "R_ERC/R_CA4DG", 
                                                   "L_ERC/L_CA2CA3", "R_ERC/R_CA2CA3",
                                                   "L_CA4DG/L_subiculum", "R_CA4DG/R_subiculum",
                                                   "L_CA2CA3/L_subiculum", "R_CA2CA3/R_subiculum",
                                                   "L_CA2CA3/L_CA1", "R_CA2CA3/R_CA1",
                                                   "L_CA2CA3/L_CA4DG", "R_CA2CA3/R_CA4DG",
                                                   "L_CA4DG/L_CA1", "R_CA4DG/R_CA1"
                                                   ))]
```

# Include sex and age
```{r}
# cog <- colnames(stream_beh_data)[129:180] # cognition

# cog <- colnames(stream_beh_data)[460:513] # working mem
# # 
# cog <- colnames(stream_beh_data)[433:438] # relational

# cog <- c("PSQI_Score", "PSQI_Comp1")

# cog <- c("Emotion_Task_Acc")
# cog <- c("Language_Task_Acc")

cog <- c("PicSeq_Unadj",
         "CardSort_Unadj",
         "IWRD_TOT",
         "ListSort_Unadj",
         "VSPLOT_TC"
         #"ProcSpeed_Unadj"
         )
  

mdl_data <- stream_beh_data[c(1:11)]
mdl_data$Age <- stream_beh_data$Age
mdl_data$Gender <- stream_beh_data$Gender
mdl_data <- merge(mdl_data, stream_beh_data[c("ID", cog)], by = "ID")

# df <- df %>% 
#   group_by(sbj,run,run_dwi,stim,weighted) %>% 
#   mutate(actsc=scale(a))

#mdl_data$PicSeq_AgeAdj <- stream_beh_data$PicSeq_AgeAdj 
mdl_melt <-
  mdl_data %>%
  melt(id = c("ID", "Age", "Gender", cog)) %>%
  group_by(ID) %>%
  mutate(valuesc = scale(value)[,1])

# mdl_melt$value.sc <- scale(mdl_melt$value)

lmer_func <- function(x) {
  f <- formula(paste("value~",x,"*variable+ Age + Gender+(1|ID)"))
  mdl <- lmer(f, control=opts.l, data = mdl_melt)
  
  mdl %>% summary()
  # plot(ggpredict(mdl,terms=c('variable','PicSeq_AgeAdj')))
  estimate_slopes(mdl,trend=x,at=c('variable'))
}

for (i in (1:length(cog))) {
  print(lmer_func(cog[i]))
}

```


# PLOTS
```{r}
(ggplot(mdl_data,
       aes(x = `R_subiculum/R_CA1`, y = IWRD_TOT)) +
  geom_point() +
  geom_smooth(method = lm, se = TRUE, size = 2, colour = "#8D406C") +
  ylab("Penn word memory correct responses") +
  xlab("Right SUB - CA1") +
  #geom_line(aes(colour = sbj)) +
  theme(
          #legend.title = element_text(colour="black", size = 12, face = "bold"),
          axis.text.x=element_text(size=10,color="black"), #, face="bold"),
          #axis.text.x=element_blank(),
          axis.text.y=element_text(size=10,color="black"),
          axis.line.y.left =element_line(size=0.5, color = "black"),
          axis.line.x.bottom =element_line(size=0.5, color = "black"),
          axis.title.x = element_text(color="black", size=15, face="bold"),# vjust=-0.2), # vjust=0.5),
          axis.title.y = element_text(color="black", size=15, face="bold", vjust=1.5),
          #legend.title = element_blank(),
          legend.text=element_text(size = 18, colour = "black"),
          legend.key.size = unit(1, "cm"),
          legend.position = 'none',
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          panel.background = element_rect(fill = "transparent", color = NA),
          plot.background = element_rect(fill = "transparent", color = NA)# vjust=0.5)
        )) %>%
      ggsave(filename = paste0("IWRD_TOT_", "R_SUB_CA1", ".png"),
                         plot = ., device = "png",
       path = "../../plots/cognition",
       scale = 1, width = 6, height = 5, dpi = 800)


#############

(ggplot(mdl_data,
       aes(x = `R_CA2CA3/CA1`, y = IWRD_TOT)) +
  geom_point() +
  geom_smooth(method = lm, se = TRUE, size = 2, colour = "#8D406C") +
  ylab("Dimensional card sorting score") +
  xlab("Right SUB - CA1") +
  #geom_line(aes(colour = sbj)) +
  theme(
          #legend.title = element_text(colour="black", size = 12, face = "bold"),
          axis.text.x=element_text(size=10,color="black"), #, face="bold"),
          #axis.text.x=element_blank(),
          axis.text.y=element_text(size=10,color="black"),
          axis.line.y.left =element_line(size=0.5, color = "black"),
          axis.line.x.bottom =element_line(size=0.5, color = "black"),
          axis.title.x = element_text(color="black", size=15, face="bold"),# vjust=-0.2), # vjust=0.5),
          axis.title.y = element_text(color="black", size=15, face="bold", vjust=1.5),
          #legend.title = element_blank(),
          legend.text=element_text(size = 18, colour = "black"),
          legend.key.size = unit(1, "cm"),
          legend.position = 'none',
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          panel.background = element_rect(fill = "transparent", color = NA),
          plot.background = element_rect(fill = "transparent", color = NA)# vjust=0.5)
        )) %>%
      ggsave(filename = paste0("IWRD_TOT_", "R_SUB_CA1", ".png"),
                         plot = ., device = "png",
       path = "../../plots/cognition",
       scale = 1, width = 6, height = 5, dpi = 800)


###################

(ggplot(mdl_data,
       aes(x = `R_CA2CA3/CA1`, y = ListSort_Unadj)) +
  geom_point() +
  geom_smooth(method = lm, se = TRUE, size = 2, colour = "#8D406C") +
  ylab("List sorting score") +
  xlab("Right CA3 - CA1") +
  #geom_line(aes(colour = sbj)) +
  theme(
          #legend.title = element_text(colour="black", size = 12, face = "bold"),
          axis.text.x=element_text(size=10,color="black"), #, face="bold"),
          #axis.text.x=element_blank(),
          axis.text.y=element_text(size=10,color="black"),
          axis.line.y.left =element_line(size=0.5, color = "black"),
          axis.line.x.bottom =element_line(size=0.5, color = "black"),
          axis.title.x = element_text(color="black", size=15, face="bold"),# vjust=-0.2), # vjust=0.5),
          axis.title.y = element_text(color="black", size=15, face="bold", vjust=1.5),
          #legend.title = element_blank(),
          legend.text=element_text(size = 18, colour = "black"),
          legend.key.size = unit(1, "cm"),
          legend.position = 'none',
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          panel.background = element_rect(fill = "transparent", color = NA),
          plot.background = element_rect(fill = "transparent", color = NA)# vjust=0.5)
        )) %>%
      ggsave(filename = paste0("ListSort_Unadj_", "R_CA3_CA1", ".png"),
                         plot = ., device = "png",
       path = "../../plots/cognition",
       scale = 1, width = 6, height = 5, dpi = 800)


################

(ggplot(mdl_data,
       aes(x = `R_CA2CA3/CA1`, y = VSPLOT_TC)) +
  geom_point() +
  geom_smooth(method = lm, se = TRUE, size = 2, colour = "#8D406C") +
  ylab("Line orientation - total correct") +
  xlab("Right CA3 - CA1") +
  #geom_line(aes(colour = sbj)) +
  theme(
          #legend.title = element_text(colour="black", size = 12, face = "bold"),
          axis.text.x=element_text(size=10,color="black"), #, face="bold"),
          #axis.text.x=element_blank(),
          axis.text.y=element_text(size=10,color="black"),
          axis.line.y.left =element_line(size=0.5, color = "black"),
          axis.line.x.bottom =element_line(size=0.5, color = "black"),
          axis.title.x = element_text(color="black", size=15, face="bold"),# vjust=-0.2), # vjust=0.5),
          axis.title.y = element_text(color="black", size=15, face="bold", vjust=1.5),
          #legend.title = element_blank(),
          legend.text=element_text(size = 18, colour = "black"),
          legend.key.size = unit(1, "cm"),
          legend.position = 'none',
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          panel.background = element_rect(fill = "transparent", color = NA),
          plot.background = element_rect(fill = "transparent", color = NA)# vjust=0.5)
        )) %>%
      ggsave(filename = paste0("VSPLOT_TC_", "R_CA3_CA1", ".png"),
                         plot = ., device = "png",
       path = "../../plots/cognition",
       scale = 1, width = 6, height = 5, dpi = 800)

```


#### END 
